baseURL: https://notes.hphk.io
enableRobotsTXT: true
title: 해피해킹 메모장
languageCode: ko-kr
theme: hugo-theme-stack
paginate: 5

# Change it to your Disqus shortname before using
# disqusShortname: hugo-theme-stack

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico

    footer:
        author: HPHK Inc.
        since: 2021
        customText: 

    dateFormat:
        # published: Jan 02, 2006
        # lastUpdated: Jan 02, 2006 15:04 MST
        published: 2006년 01월 02일
        lastUpdated: 2006년 01월 02일 15:04 MST

    sidebar:
        emoji: 👾
        # subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        # avatar:
        #     local: true
        #     src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances
        utterances:
            repo: hphkinc/notes
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    # widgets:
    #     enabled:
    #         # - search
    #         # - archives
    #         - tag-cloud

    #     # archives:
    #     #     limit: 5

    #     tagCloud:
    #         limit: 15

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: og-image.png

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: false
        content:
            enabled: false

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        # - identifier: about
        #   name: About
        #   url: about
        #   weight: -90
        #   pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
